# 3. diena - JSON, CSV un Pandas pamati

## Notebook mērķis

Šajā notebook soli pa solim apskatīsim, kā:
- nolasīt vienkāršu `JSON` failu ar Python standarta bibliotēku
- apskatīt `JSON` struktūru
- strādāt ar ligzdotu `JSON`
- nolasīt `CSV` failus ar `pandas`
- apskatīt `DataFrame`
- atlasīt, filtrēt, kārtot un pārveidot datus
- apvienot tabulas ar `concat()` un `merge()`
- eksportēt rezultātus uz `CSV` un `JSON`

## Šajā nodarbībā izmantotie faili

Mēs izmantosim paraugdatus no mapes `data/day3/`:
- `products_basic.json`
- `orders_nested.json`
- `products.csv`
- `sales_january.csv`
- `sales_february.csv`

## Svarīgi

Izpildiet notebook no augšas uz leju. Vēlākās šūnas izmanto mainīgos, kas
izveidoti iepriekšējās šūnās.

In [1]:
import json # iebūvēta Python bibliotēka JSON datu apstrādei
from pathlib import Path # arī iebūvēta bibliotēka, kas ļauj strādāt ar failu ceļiem
print("Varam sākt darbu ar JSON datiem!") # vienkārša paziņojuma izvadīšana, lai informētu, ka skripts ir sācies

Varam sākt darbu ar JSON datiem!

In [2]:
file_path = Path(r"..\data\day3\products_basic.json") # r vajadzīs ja lietojam \ Windows
# pārliecinamies, ka fails eksistē, pirms mēģinām to atvērt
assert file_path.exists(), f"Fails {file_path} neeksistē!" # ja fails neeksistē, tiks izmests kļūdas paziņojums

In [3]:
# es varētu vienkārši atvērt failu un ielādēt tekstu
with open(file_path, "r", encoding="utf-8") as f: # atveram failu lasīšanas režīmā ar UTF-8 kodējumu
    json_text = f.read() # nolasām visu faila saturu kā tekstu
# pirmos 100 simbolus
print(json_text[:100]) # izvadām pirmos 100 simbolus, lai redzētu, kā izskatās JSON dati kā teksts

[
  {
    "product_id": "P001",
    "name": "Notebook A5",
    "category": "Office",
    "price": 2.

In [4]:
# ja šis string ir korekts json tad varam to pārvērst par Python datu struktūru
data = json.loads(json_text) # json.loads() funkcija pārvērš JSON tekstu par Python datu struktūru (parasti vārdnīcu vai sarakstu)
print(type(data)) # izvadām datu tipu, lai redzētu, kāda Python datu struktūra ir izveidota

<class 'list'>

In [5]:
# paprasam cik mums elementu ir datu struktūrā
print("Mums ir", len(data), "produkti!") # izvadām, cik elementu ir datu struktūrā, kas, iespējams, ir saraksts ar produktiem

Mums ir 10 produkti!

In [6]:
# apskatam pirmos tris sarakasta elementus
print(data[:3]) # izvadām pirmos trīs elementus no datu struktūras, kas, iespējams, ir saraksts ar produktiem

[{'product_id': 'P001', 'name': 'Notebook A5', 'category': 'Office', 'price': 2.49, 'in_stock': True, 'supplier': 'Baltic Paper'}, {'product_id': 'P002', 'name': 'Ballpoint Pen Blue', 'category': 'Office', 'price': 0.89, 'in_stock': True, 'supplier': 'Riga Supplies'}, {'product_id': 'P003', 'name': 'Desk Lamp Mini', 'category': 'Electronics', 'price': 18.5, 'in_stock': False, 'supplier': 'Home Light'}]

In [7]:
# izvadīsim pirmos 4 ar for ciklu
for element in data[:4]: # iterējam cauri pirmajiem četriem elementiem datu struktūrā
    print(element) # izvadām katru elementu atsevišķi, lai redzētu, kā tie izskatās

{'product_id': 'P001', 'name': 'Notebook A5', 'category': 'Office', 'price': 2.49, 'in_stock': True, 'supplier': 'Baltic Paper'}
{'product_id': 'P002', 'name': 'Ballpoint Pen Blue', 'category': 'Office', 'price': 0.89, 'in_stock': True, 'supplier': 'Riga Supplies'}
{'product_id': 'P003', 'name': 'Desk Lamp Mini', 'category': 'Electronics', 'price': 18.5, 'in_stock': False, 'supplier': 'Home Light'}
{'product_id': 'P004', 'name': 'Water Bottle 750ml', 'category': 'Lifestyle', 'price': 7.2, 'in_stock': True, 'supplier': 'Nordic Home'}

In [8]:
# apskatīsim pirmo elementu
first_element = data[0] # piekļūstam pirmajam elementam datu struktūrā
# kāds tips
print(type(first_element)) # izvadām pirmā elementa datu tipu, lai redzētu, kāda Python datu struktūra tas ir
# izvadam pašu elementu
print(first_element) # izvadām pirmo elementu, lai redzētu, kā tas izskatās

<class 'dict'>
{'product_id': 'P001', 'name': 'Notebook A5', 'category': 'Office', 'price': 2.49, 'in_stock': True, 'supplier': 'Baltic Paper'}

In [9]:
# tātad dict datu tips ir vārdnīca, kas satur atslēgas un vērtības, piemēram "id": 1, "name": "Product 1" utt.
# pamatīpāšiba šadam datu tipam ir tā, ka varam piekļūt vērtībām pēc atslēgām, 
# piemēram first_element["id"] mums dos 1, first_element["name"] mums dos "Product 1" utt.
# zinot atslēgu mēs varam ļoti ātri (konstantā laikā) piekļūt vērtībai, kas ir ļoti ērti datu apstrādē
# pat ja vārdnīca ir ļoti liela, piekļuve vērtībai pēc atslēgas būs ātra, 
# jo Python izmanto hash tabulas, lai organizētu vārdnīcas datus.
# citās valodas dictionary sauc arī par hash map, hash table, associative array, map, dict, un object  utt.

In [10]:
# kādas atslēgas ir pirmajam elementam?
print(first_element.keys()) # izvadām pirmā elementa atslēgas, lai redzētu, kādi dati ir pieejami katram produktam

dict_keys(['product_id', 'name', 'category', 'price', 'in_stock', 'supplier'])

In [11]:
# ja es zinu atslēgu piemēram "name" es varu piekļūt produkta nosaukumam ļoti ātri pat lielai vārdnīcai
print(first_element["name"]) # izvadām pirmā elementa "name" atslēgas vērtību, lai redzētu produkta nosaukumu

Notebook A5

In [12]:
# kā būtu ar cenu?
print(first_element["price"]) # izvadām pirmā elementa "price" atslēgas vērtību, lai redzētu produkta cenu

2.49

In [13]:
# es protams varētu arī mainīt vērtību tieši konkreta elementa atslēgai
# mēs varētu nomainīt pirmā produkta cenu uz 2.75
first_element["price"] = 2.75 # mainām pirmā produkta "price" atslēgas vērtību uz 2.75
print(first_element["price"]) # izvadām pirmā elementa "price" atslēgas vērtību, lai redzētu, ka tā ir mainījusies uz 2.75
# izdrukajām arī pirmo data elementu
print(data[0]["price"]) # izvadām pirmā elementa "price" atslēgas vērtību, lai redzētu, ka tā ir mainījusies uz 2.75

2.75
2.75

In [15]:
# apstādināsim pieziemjū grāmatu šeit
# assert False, "Pietiek ar JSON datu apstrādi uz brīdi!" # apstādinām skriptu ar kļūdas paziņojumu, lai informētu, ka esam beiguši darbu ar JSON datiem šodien

In [21]:
# mēs varētu atrast produkuts ar cenu zem 2.50
TARGET_PRICE = 3.50 # definējam mērķa cenu, zem kuras meklēsim produktus
# sāksim ar izdruku
for product in data: # iterējam cauri visiem produktiem datu struktūrā
    if product["price"] < TARGET_PRICE: # pārbaudām, vai produkta "price" atslēgas vērtība ir mazāka par mērķa cenu
        print(product) # ja nosacījums ir izpildīts, izvadām produktu, lai redzētu, kuri produkti maksā mazāk par mērķa cenu

{'product_id': 'P001', 'name': 'Notebook A5', 'category': 'Office', 'price': 2.75, 'in_stock': True, 'supplier': 'Baltic Paper'}
{'product_id': 'P002', 'name': 'Ballpoint Pen Blue', 'category': 'Office', 'price': 0.89, 'in_stock': True, 'supplier': 'Riga Supplies'}
{'product_id': 'P007', 'name': 'Sticky Notes Set', 'category': 'Office', 'price': 3.1, 'in_stock': True, 'supplier': 'Baltic Paper'}

In [23]:
# vēl var būt moments kā kādai vārdnīcai nav konkrētas atslēgas piemēram nav "supplier"
# kā to pārbaudīt? dictionary in Python dod iespēju ļoti ātri pārbaudīt, vai konkrēta atslēga ir pieejama vārdnīcā
if "supplier" in first_element: # pārbaudām, vai "supplier" atslēga ir pieejama pirmajā elementā
    print("Mums ir supplier! atslēga")
    print("Supplier vērtība ir:", first_element["supplier"]) # ja "supplier" atslēga ir pieejama, izvadām tās vērtību
else:
    print("Mums nav supplier! atslēga") # ja "supplier" atslēga nav pieejama, izvadām paziņojumu, ka tā nav pieejama

Mums ir supplier! atslēga
Supplier vērtība ir: Baltic Paper

In [24]:
# ja negribās pārbaudīt katru elementu, vai tam ir "supplier" atslēga, varam arī izmantot .get() metodi, kas ļauj norādīt noklusējuma vērtību, ja atslēga nav pieejama
supplier_value = first_element.get("supplier", "Nav pieejams") # mēģinam un padodam noklusēto vērtibu "Nav pieejams", ja "supplier" atslēga nav pieejama
print("Supplier vērtība ar .get() metodi ir:", supplier_value) # izvadām "supplier" vērtību, izmantojot .get() metodi, lai redzētu, vai tā ir pieejama vai tiek izmantota noklusējuma vērtība

Supplier vērtība ar .get() metodi ir: Baltic Paper

In [25]:
# kas būs ja meklēsim neeksistējošu atslēgu ar .get() metodi?
non_existent_value = first_element.get("nepareizaastlēga", "Nav pieejams") # mēģinam meklēt neeksistējošu atslēgu "non_existent_key" un padodam noklusēto vērtibu "Nav pieejams"
print("Neeksistējošas atslēgas vērtība ar .get() metodi ir:", non_existent_value) # izvadām neeksistējošas atslēgas vērtību, lai redzētu, ka tiek izmantota noklusējuma vērtība "Nav pieejams"

Neeksistējošas atslēgas vērtība ar .get() metodi ir: Nav pieejams

In [26]:
# atgriežamies pie mūsu lēto produktu meklēšanas
# mēs gribētu saglabāt jaunā lēto produktu sarasta visus produktus zem 3.50
cheap_products = [] # izveidojam tukšu sarakstu, kurā saglabāsim lētos produktus
# sarakstam ir jēga, ja glabasim homogēnus datus, piemēram vārdnīcas, kas apraksta produktus, jo saraksts ļauj mums saglabāt vairākus produktus vienuviet
for product in data: # iterējam cauri visiem produktiem datu struktūra
    if product["price"] < TARGET_PRICE: # pārbaudām, vai produkta "price" atslēgas vērtība ir mazāka par mērķa cenu
        cheap_products.append(product) # ja nosacījums ir izpildīts, pievienojam produktu lēto produktu sarakstam
# šeit viss būs labi ja visiem produktiem ir cena definēta ienākošaja json
print("Mums ir", len(cheap_products), "lēti produkti zem", TARGET_PRICE) # izvadām, cik lēto produktu ir atrasts zem mērķa cenas
print("Lēto produktu saraksts ir:", cheap_products) # izvadām lēto produktu sarakstu, lai redzētu, kuri produkti ir zem mērķa cenas
for product in cheap_products: # iterējam cauri lēto produktu sarakstam
    print(product["name"], "cena ir", product["price"]) # izvadām katra lētā produkta nosaukumu un cenu, lai redzētu, kuri produkti ir zem mērķa cenas un kādas ir to cenas

Mums ir 3 lēti produkti zem 3.5
Lēto produktu saraksts ir: [{'product_id': 'P001', 'name': 'Notebook A5', 'category': 'Office', 'price': 2.75, 'in_stock': True, 'supplier': 'Baltic Paper'}, {'product_id': 'P002', 'name': 'Ballpoint Pen Blue', 'category': 'Office', 'price': 0.89, 'in_stock': True, 'supplier': 'Riga Supplies'}, {'product_id': 'P007', 'name': 'Sticky Notes Set', 'category': 'Office', 'price': 3.1, 'in_stock': True, 'supplier': 'Baltic Paper'}]
Notebook A5 cena ir 2.75
Ballpoint Pen Blue cena ir 0.89
Sticky Notes Set cena ir 3.1

In [27]:
# labāk būtu pārbaudīt vai "price" atslēga ir pieejama katram produktam, pirms mēģinām to izmantot, lai izvairītos no kļūdām, ja kādam produktam nav definēta cena
cheap_products = [] # izveidojam tukšu sarakstu, kurā saglabāsim lētos produktus
for product in data: # iterējam cauri visiem produktiem datu struktūra
    price = product.get("price") # mēģinam iegūt produkta cenu, izmantojot .get() metodi, lai izvairītos no kļūdas, ja "price" atslēga nav pieejama
    # tātad get ja nav uzdota vērtība, tad atgriezīs None, tāpēc varam pārbaudīt vai price nav None un vai price ir mazāka par TARGET_PRICE
    if price is not None and price < TARGET_PRICE: # pārbaudām, vai cena ir definēta un mazāka par mērķa cenu
        cheap_products.append(product) # ja nosacījums ir izpildīts, pievienojam produktu lēto produktu sarakstam

In [29]:
# izdrukājam vēlreiz lētos produktus pa vienam
for product in cheap_products: # iterējam cauri lēto produktu sarakstam
    print(product) # izvadām katru lēto produktu, lai redzētu, kuri produkti ir zem mērķa cenas un kādas ir to cenas
    print(product["name"], "cena ir", product["price"]) # izvadām katra lētā produkta nosaukumu un cenu, lai redzētu, kuri produkti ir zem mērķa cenas un kādas ir to cenas

{'product_id': 'P001', 'name': 'Notebook A5', 'category': 'Office', 'price': 2.75, 'in_stock': True, 'supplier': 'Baltic Paper'}
Notebook A5 cena ir 2.75
{'product_id': 'P002', 'name': 'Ballpoint Pen Blue', 'category': 'Office', 'price': 0.89, 'in_stock': True, 'supplier': 'Riga Supplies'}
Ballpoint Pen Blue cena ir 0.89
{'product_id': 'P007', 'name': 'Sticky Notes Set', 'category': 'Office', 'price': 3.1, 'in_stock': True, 'supplier': 'Baltic Paper'}
Sticky Notes Set cena ir 3.1

In [31]:
# tagad saglabāsim šos lētos produktus atpakāl JSON failā, lai varētu tos izmantot vēlāk
output_file_path = Path(r"..\data\day3\cheap_products.json") # definējam ceļu, kur saglabāsim lēto produktu JSON failu
# vispirms vienkāršais glabājums
with open(output_file_path, "w", encoding="utf-8") as f: # atveram failu rakstīšanas režīmā ar UTF-8 kodējumu
    json.dump(cheap_products, f, ensure_ascii=False, indent=2) # json.dump() funkcija pārvērš Python datu struktūru par JSON tekstu un saglabā to failā, nodrošinot, ka tiek izmantots UTF-8 kodējums un formatējot JSON ar 4 atstarpēm

In [32]:
# ja json domāts tikai apmaiņai starp dažādām datoru sistēmam
# tad varam nelikt indent
# lietojam with lai automātiski aizvērtu failu pēc rakstīšanas, un nodrošinām UTF-8 kodējumu, lai saglabātu latviešu valodas simbolus pareizi
with open("../data/day3/cheap_products_no_indent.json", "w", encoding="utf-8") as f: # atveram failu rakstīšanas režīmā ar UTF-8 kodējumu
    json.dump(cheap_products, f, ensure_ascii=False) # json.dump() funkcija pārvērš Python datu struktūru par JSON tekstu un saglabā to failā, nodrošinot, ka tiek izmantots UTF-8 kodējums, bet neformatējot JSON ar atstarpēm
# šeit fails jaur ir ciet

## Darbs ar nested JSON

JSON var būt daudzus līmeņu saraksts, un katrs elements var būt atslēgu un vērtību pāris, kur vērtība var būt arī saraksts vai cits JSON objekts. Šādu struktūru sauc par ligzdotu (nested) JSON.

In [33]:
# apskatīsm orders_nested.json kurš atrodas data/day3/orders_nested.json
with open("../data/day3/orders_nested.json", "r", encoding="utf-8") as f: # atveram orders_nested.json failu lasīšanas režīmā ar UTF-8 kodējumu
    orders_data = json.load(f) # json.load() funkcija nolasām JSON datus no faila un pārvēršam tos par Python datu struktūru
# ko mēs esam ieguvušu atmiņā?
print(type(orders_data)) # izvadām orders_data datu tipu, lai redz

<class 'dict'>

In [34]:
# kādas tad mums ir augstākā līmeņa atslēgas?
print(orders_data.keys()) # izvadām orders_data atslēgas, lai redzētu, kādi dati ir pieejami augstākajā līmenī

dict_keys(['report_name', 'generated_at', 'currency', 'orders'])

In [35]:
# kāds datu tips ir orders vērtībai?
print(type(orders_data["orders"])) # izvadām orders_data "orders" atslēgas vērtības datu tipu, lai redzētu, kāda Python datu struktūra tā ir

<class 'list'>

In [36]:
# cik mums ir to pasūtījumu?
print("Mums ir", len(orders_data["orders"]), "pasūtījumi!") # izvadām, cik pasūtījumu ir "orders" atslēgas vērtībā, lai redzētu, cik pasūtījumu ir datu struktūrā

Mums ir 5 pasūtījumi!

In [37]:
# kas ir pirmais pasūtījums?
print(orders_data["orders"][0]) # izvadām pirmo pasūtījumu no "orders" atslēgas vērtības, lai redzētu, kā izskatās pirmais pasūtījums datu struktūrā

{'order_id': 1001, 'customer': {'customer_id': 'C001', 'name': 'Anna Ozola', 'city': 'Riga', 'loyalty_tier': 'gold'}, 'items': [{'product_id': 'P001', 'quantity': 3, 'unit_price': 2.49}, {'product_id': 'P005', 'quantity': 1, 'unit_price': 6.99}], 'payment': {'method': 'card', 'status': 'paid'}, 'delivery': {'type': 'parcel', 'cost': 2.5}}

In [38]:
# kādas ir pirmā pasūtījuma atslēgas?
print(orders_data["orders"][0].keys()) # izvadām pirmā pasūt

dict_keys(['order_id', 'customer', 'items', 'payment', 'delivery'])

In [39]:
# mūs interesē pasūtījumi
print(orders_data["orders"][0]["items"]) # izvadām pirmā pasūtījuma "items" atslēgas vērtību, lai redzētu, kādas ir pirmā pasūtījuma preces

[{'product_id': 'P001', 'quantity': 3, 'unit_price': 2.49}, {'product_id': 'P005', 'quantity': 1, 'unit_price': 6.99}]

In [40]:
# kas būs pirmā pasūtījuma pirmā prece?
print(orders_data["orders"][0]["items"][0]) # izvadām pirmā

{'product_id': 'P001', 'quantity': 3, 'unit_price': 2.49}

In [42]:
# kāda ir pirmā pasūtījuma pirmās preces vienības cena?
print(orders_data["orders"][0]["items"][0]["unit_price"]) # izvadām

2.49

In [43]:
# izveidosim jaunu sarakstu ar lētam preces kas pasūtītas
# mūsu glabāšanas struktūra būs šāda:
# saraksts ar pasutījumiem
# katrs pasūtījums būs vārdnīca ar sekojošam atslēgam:
# order_id - pasūtījuma id
# customer_name - klients, kas veica pasūtījumu
# customer_city - klienta pilsēta
# produkta_id - pasūtītā produkta id
# quantity - pasūtītais daudzums
# product_price - pasūtītā produkta cena
TARGET_PRICE = 3.50 # definējam mērķa cenu, zem kuras meklēsim lētas preces
cheap_order_items = [] # izveidojam tukšu sarakstu, kurā saglabāsim lētas preces no pasūtījumiem
# ejam cauri orders
for order in orders_data["orders"]: # iterējam cauri visiem pasūtījumiem "orders" atslēgas vērtībā
    # jāpiemin, ka ieteiktu izmanot get visur kur iespējam nav vērtības
    order_id = order.get("order_id") # iegūstam pasūtījuma id
    customer_name = order["customer"].get("name") # iegūstam klienta vārdu no "customer" atslēgas vērtības, kas ir vārdnīca ar klienta informāciju
    customer_city = order["customer"].get("city") # iegūstam klienta pilsētu no "customer" atslēgas vērtības
    for item in order["items"]: # iterējam cauri visām precēm "items" atslēgas vērtībā, kas ir saraksts ar precēm pasūtījumā
        product_id = item.get("product_id") # iegūstam produkta id no "product_id" atslēgas vērtības, kas ir vārdnīca ar preces informāciju
        quantity = item.get("quantity") # iegūstam pasūtīto daudzumu no "quantity" atslēgas vērtības
        product_price = item.get("unit_price") # iegūstam produkta cenu no "unit_price" atslēgas vērtības
        if product_price < TARGET_PRICE: # pārbaudām, vai produkta cena ir mazāka par mērķa cenu
            cheap_order_items.append({ # ja nosacījums ir izpildīts, pievienojam preci lētu preču sarakstam kā vārdnīcu ar sekojošām atslēgām un vērtībām:
                "order_id": order_id, # pasūtījuma id
                "customer_name": customer_name, # klienta vārds
                "customer_city": customer_city, # klienta pilsēta
                "product_id": product_id, # produkta id
                "quantity": quantity, # pasūtītais daudzums
                "product_price": product_price # produkta cena
            })

# cik lētos pasūtijumus savācām?
print("Mums ir", len(cheap_order_items), "lēti pasūtījuma preces zem", TARGET_PRICE) # izvadām, cik lētu pasūtījuma preces ir atrasts zem mērķa cenas

Mums ir 4 lēti pasūtījuma preces zem 3.5

In [44]:
# izdrukāsim šos lētos pasūtijumus
for item in cheap_order_items: # iterējam cauri lētu pasūtījuma preču sarakstam
    print(item) # izvadām katru lētu pasūtījuma preci, lai redzētu, kuri pasūtījuma preces ir zem mērķa cenas

{'order_id': 1001, 'customer_name': 'Anna Ozola', 'customer_city': 'Riga', 'product_id': 'P001', 'quantity': 3, 'product_price': 2.49}
{'order_id': 1004, 'customer_name': 'Roberts Kalnins', 'customer_city': 'Riga', 'product_id': 'P002', 'quantity': 10, 'product_price': 0.89}
{'order_id': 1004, 'customer_name': 'Roberts Kalnins', 'customer_city': 'Riga', 'product_id': 'P007', 'quantity': 4, 'product_price': 3.1}
{'order_id': 1004, 'customer_name': 'Roberts Kalnins', 'customer_city': 'Riga', 'product_id': 'P001', 'quantity': 2, 'product_price': 2.49}

In [45]:
# es pielikšu pirmo preci klāt beigās kā duplikātu
cheap_order_items.append(cheap_order_items[0]) # pievienojam pirmo lētu pasūtījuma preci saraksta beigās, lai izveidotu duplikātu
print("Pēc duplikāta pievienošanas mums ir", len(cheap_order_items  ), "lēti pasūtījuma preces zem", TARGET_PRICE) # izvadām, cik lētu pasūtījuma preces ir atrasts zem mērķa cenas pēc duplikāta pievienošanas

Pēc duplikāta pievienošanas mums ir 5 lēti pasūtījuma preces zem 3.5

In [46]:
# vēlreiz izdrukājam lētos pasūtijumus, lai redzētu, ka duplikāts ir pievienots
for item in cheap_order_items: # iterējam cauri lētu pasūtījuma preču sarakstam
    print(item) # izvadām katru lētu pasūtījuma preci, lai redzētu, kuri pasūtījuma preces ir zem mērķa cenas

{'order_id': 1001, 'customer_name': 'Anna Ozola', 'customer_city': 'Riga', 'product_id': 'P001', 'quantity': 3, 'product_price': 2.49}
{'order_id': 1004, 'customer_name': 'Roberts Kalnins', 'customer_city': 'Riga', 'product_id': 'P002', 'quantity': 10, 'product_price': 0.89}
{'order_id': 1004, 'customer_name': 'Roberts Kalnins', 'customer_city': 'Riga', 'product_id': 'P007', 'quantity': 4, 'product_price': 3.1}
{'order_id': 1004, 'customer_name': 'Roberts Kalnins', 'customer_city': 'Riga', 'product_id': 'P001', 'quantity': 2, 'product_price': 2.49}
{'order_id': 1001, 'customer_name': 'Anna Ozola', 'customer_city': 'Riga', 'product_id': 'P001', 'quantity': 3, 'product_price': 2.49}

In [47]:
# salīdzināsim pirmo ar pēdejo ierakstu/vārdnīcu
print("Pirmais ieraksts ir:", cheap_order_items[0]) # izvadām pirmo lētu pasūtījuma preci, lai redzētu, kā tā izskatās
print("Pēdējais ieraksts ir:", cheap_order_items[-1]) #
# vai tie ir vienādi pēc SATURA?
print("Vai pirmā un pēdējā ieraksta saturs ir vienāds?", cheap_order_items[0] == cheap_order_items[-1]) # izvadām, vai pirmā un pēdējā lētu pasūtījuma preces saturs ir vienāds, lai redzētu, vai duplikāts ir veiksmīgi pievienots

Pirmais ieraksts ir: {'order_id': 1001, 'customer_name': 'Anna Ozola', 'customer_city': 'Riga', 'product_id': 'P001', 'quantity': 3, 'product_price': 2.49}
Pēdējais ieraksts ir: {'order_id': 1001, 'customer_name': 'Anna Ozola', 'customer_city': 'Riga', 'product_id': 'P001', 'quantity': 3, 'product_price': 2.49}
Vai pirmā un pēdējā ieraksta saturs ir vienāds? True

In [48]:
# saglabājam šos lētos pasūtijumus
with open("../data/day3/cheap_order_items.json", "w", encoding="utf-8") as f: # atveram failu rakstīšanas režīmā ar UTF-8 kodējumu
    json.dump(cheap_order_items, f, ensure_ascii=False, indent=2) # json.dump() funkcija pārvērš Python datu struktūru par JSON tekstu un saglabā to failā, nodrošinot, ka tiek izmantots UTF-8 kodējums un formatējot JSON ar 4 atstarpēm

In [ ]:
# tagad par duplikātu atrašanu
# mēs varētu tagad visus ierakstus / rindiņas / vārdnīcas salīdzināt savā starpā un atrast duplikātus, 
# bet tas būtu ļoti neefektīvi, jo mums ir 1000+ ieraksti, un tas nozīmētu 1 000 000+ salīdzinājumu, kas var aizņemt ļoti ilgu laiku
# līdz ar to labāk būt pārbaudīt pēc kādas atslēgas vai atslēgām, kas varētu identificēt duplikātus, piemēram "order_id" un "product_id", jo ja mums ir divi ieraksti ar vienādu "order_id" un "product_id", tad mēs varam būt diezgan droši, ka tie ir duplikāti, un tādā veidā mēs varam atrast duplikātus daudz ātrāk.

## Darbs ar Pandām

Pandas ir jaudīga datu analīzes bibliotēka, kas ļauj viegli manipulēt ar tabulveida datiem. Ar Pandām var nolasīt CSV failus, veikt dažādas datu transformācijas, kārtot un filtrēt datus, apvienot tabulas un eksportēt rezultātus.

Mājas lapa: https://pandas.pydata.org/

Līdz šim mēs strādājam tikai ar iebūvētam bibliotekām, bet Pandas ir jāinstalē atsevišķi, izmantojot pip:


```
pip install pandas
```

In [49]:
# ielādēsim pandas 
import pandas as pd # pd ir de fakto saīsinājums /alias importējot pandas
# vienkārši visiem slinkums rakstīt pandas visu laiku
# kāda versija
print("Mums ir pandas versija:", pd.__version__) # izvadām pandas versiju, lai redzētu, kāda pandas versija ir instalēta

Mums ir pandas versija: 3.0.2

In [ ]:
# vēl noderētu openpyxl, lai strādātu ar Excel datiem,
# to uzstāda ar pip install openpyxl komandu, un tas ļauj mums lasīt un rakstīt Excel failus, kas var būt ļoti noderīgi datu apstrādē un analīzē, jo Excel ir ļoti populārs rīks datu glabāšanai un apstrādei, un ar openpyxl mēs varam viegli integrēt Excel datus mūsu Python skriptos.

In [ ]:
# !pip install pandas openpyxl 
# atkomntējam iepriekšējo rindiņu, ja vēlamies uzstādid pandas un openpyxl excel darbam
# iespējams pēc tam vēlams pārstartēt pašu piezīmju grāmatu
# uzstādām pandas un openpyxl, lai varētu strādāt ar datiem un Excel failiem nākotnē, un tas ļaus mums viegli lasīt un rakstīt Excel failus, kas var būt ļoti noderīgi datu apstrādē un analīzē, jo Excel ir ļoti populārs rīks datu glabāšanai un apstrādei, un ar openpyxl mēs varam viegli integrēt Excel datus mūsu Python skriptos.

Requirement already satisfied: pandas in d:\Github\RTU_Python_CSP\.venv\Lib\site-packages (3.0.2)
Requirement already satisfied: openpyxl in d:\Github\RTU_Python_CSP\.venv\Lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=2.3.3 in d:\Github\RTU_Python_CSP\.venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\Github\RTU_Python_CSP\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\Github\RTU_Python_CSP\.venv\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: et-xmlfile in d:\Github\RTU_Python_CSP\.venv\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in d:\Github\RTU_Python_CSP\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# pandas ir domātas darbam ar tabulām - DataFrame ir pandas datu struktūra, kas ir līdzīga tabulai ar rindām un kolonnām, un tā ļauj mums viegli manipulēt ar datiem, piemēram, filtrēt, grupēt, apkopot, un veikt dažādas analīzes un transformācijas uz datiem. DataFrame ir ļoti noderīgs rīks datu apstrādē un analīzē, jo tas nodrošina ērtu un efektīvu veidu, kā strādāt ar lieliem datu kopumiem un veikt dažādas operācijas uz tiem.

In [53]:
# atvērsim products_basic.json ar pandas
df = pd.read_json("../data/day3/products_basic.json") # pd.read_json() funkcija nolasām JSON datus no faila un pārvēršam tos par pandas DataFrame datu struktūru
# df if standarta mainīgā nosaukums vispārīg dataframe tabulām
# protams varam vēlāk rakstīt garākus nosaukums piem
# product_df utml
df # izvadām DataFrame, lai redzētu, kā izskatās

  product_id                name     category  price  in_stock       supplier
0       P001         Notebook A5       Office   2.49      True   Baltic Paper
1       P002  Ballpoint Pen Blue       Office   0.89      True  Riga Supplies
2       P003      Desk Lamp Mini  Electronics  18.50     False     Home Light
3       P004  Water Bottle 750ml    Lifestyle   7.20      True    Nordic Home
4       P005      USB-C Cable 1m  Electronics   6.99      True    Tech Bridge
5       P006  Coffee Mug Classic      Kitchen   4.75      True       Ceramica
6       P007    Sticky Notes Set       Office   3.10      True   Baltic Paper
7       P008      Wireless Mouse  Electronics  14.90      True    Tech Bridge
8       P009     Tote Bag Canvas    Lifestyle   5.50     False    Urban Basic
9       P010      Tea Box Herbal      Kitchen   6.40      True     Green Leaf

In [ ]:
# tagad varam uzreiz saglabāt kā CSV vispirms
df.to_csv("../data/day3/products_basic.csv", index=False, encoding="utf-8") # df.to_csv() funkcija pārvērš DataFrame par CSV tekstu un saglabā to failā, 
# nodrošinot, ka netiek saglabāts indekss un tiek izmantots UTF-8 kodējums

In [56]:
# līdzīgi varam arī saglabāt excel
df.to_excel("../data/day3/products_basic.xlsx", index=False)

In [ ]:
# kurā formātā labāk glabāt?
# CSV ir viegli lasāms 
# pēc būtības CSV ir tāds pats teksta formāts
# kā .txt, kā .py, kā .json, kā .xml, kā .html utt.
# tas ir viegli lasāms un saprotams cilvēkiem, un to var atvērt ar jebkuru teksta redaktoru, un tas ir arī viegli apstrādājams ar dažādām programmēšanas valodām, jo tas ir vienkāršs teksta formāts, kurā dati ir atdalīti ar komatiem vai citiem atdalītājiem, un katra rinda parasti atbilst vienam datu ierakstam. CSV ir ļoti populārs formāts datu glabāšanai un apmaiņai, jo tas ir vienkāršs, viegli lasāms un plaši atbalstīts.
# problema ar CSV ir ka tas nav īsti standartizēts
# līdz ar to dažādi rīki var interpretēt CSV failus atšķirīgi, piemēram, kā tiek apstrādāti teksta lauki, kas satur komatus, kā tiek apstrādāti datumi, kā tiek apstrādāti nulles vērtības utt. Tas var radīt problēmas datu apstrādē un analīzē, jo dažādi rīki var interpretēt CSV failus atšķirīgi, un tas var novest pie nepareiziem rezultātiem vai kļūdām datu apstrādē. Tāpēc ir svarīgi būt uzmanīgiem, strādājot ar CSV failiem, un pārliecināties, ka tie tiek interpretēti pareizi, lai izvairītos no problēmām datu apstrādē un analīzē.
# līdz ar to glabājot excel mēs zaudējam cilvekam pieejamu lasāmību un rediģēšanu
# bet iegūstam stingrākus datu tipus

In [ ]:
# apkskatīsm kādi datu tipi ir mūsu DataFrame tabulai
df.dtypes
# te mēs redzam, ka atsķirība no Python vispār,
#  Pandas(caur numpy) piedāvā detalizētakus datu tipus

product_id        str
name              str
category          str
price         float64
in_stock         bool
supplier          str
dtype: object

In [58]:
# apskatamies vispārējo info
df.info() # df.info() funkcija izvadām vispārīgu informāciju par DataFrame, tostarp datu tipu, nulles vērtībām, un atmiņas patēriņu

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  10 non-null     str
 1   name        10 non-null     str
 2   category    10 non-null     str
 3   price       10 non-null     float64
 4   in_stock    10 non-null     bool
 5   supplier    10 non-null     str
dtypes: bool(1), float64(1), str(4)
memory usage: 542.0 bytes

In [59]:
# pieliksim klāt kolonu quantity un būs mums katrā 25 produkti
df["quantity"] = 25 # pievienojam jaunu kolonu "quantity" ar vērtību 25 katram produktam DataFrame, lai redzētu, kā pievienot jaunu kolonu ar vienādu vērtību visiem ierakstiem
# tagad ja mums ir liela tabula/dataframe mēs negribam visu tabulu attēlot pietiek ar galveni
df.head() # pēc noklusējam pirmās 5

,product_id,name,category,price,in_stock,supplier,quantity
0,P001,Notebook A5,Office,2.49,True,Baltic Paper,25
1,P002,Ballpoint Pen Blue,Office,0.89,True,Riga Supplies,25
2,P003,Desk Lamp Mini,Electronics,18.50,False,Home Light,25
3,P004,Water Bottle 750ml,Lifestyle,7.20,True,Nordic Home,25
4,P005,USB-C Cable 1m,Electronics,6.99,True,Tech Bridge,25

In [60]:
# apskatamies asti bet tikai 3
df.tail(3) # izvadām pēdējās 3 rindas no DataFrame, lai redzētu, kā izskatās tabulas beigas

,product_id,name,category,price,in_stock,supplier,quantity
7,P008,Wireless Mouse,Electronics,14.9,True,Tech Bridge,25
8,P009,Tote Bag Canvas,Lifestyle,5.5,False,Urban Basic,25
9,P010,Tea Box Herbal,Kitchen,6.4,True,Green Leaf,25

In [76]:
# lietlākam tabulām head un tail vietā var izmantot arī sample
df.sample(4, random_state=2026) 
# df.sample(4) # katru reizi cits sample, jo nav uzstādīts random_state
# izvadām nejauši izvēlētas 4 rindas no DataFrame,
#  lai redzētu, kā izskatās nejauši izvēlēti ieraksti,
#  un nodrošinām reproducējamību ar random_state parametru

,product_id,name,category,price,in_stock,supplier,quantity
7,P008,Wireless Mouse,Electronics,14.9,True,Tech Bridge,25
3,P004,Water Bottle 750ml,Lifestyle,7.2,True,Nordic Home,25
9,P010,Tea Box Herbal,Kitchen,6.4,True,Green Leaf,25
8,P009,Tote Bag Canvas,Lifestyle,5.5,False,Urban Basic,25

In [77]:
# apskatamies datu tipus atkal
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  10 non-null     str
 1   name        10 non-null     str
 2   category    10 non-null     str
 3   price       10 non-null     float64
 4   in_stock    10 non-null     bool
 5   supplier    10 non-null     str
 6   quantity    10 non-null     int64
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 622.0 bytes

In [78]:
# es varu iedot konkrētu datu tipu konkrētai kolonnai, piemēram quantity ir int, bet es varu to pārvērst par float
# je es gribētu ietaupīt vietu, tad varētu pateikt konkrētu int izmēru
# piemēram ja es zinu ka nekad vērtība quantity nebūs lielāka par 255, tad varu izmantot uint8, kas aizņem tikai 1 baitu atmiņas, nevis int64, kas aizņem 8 baitus
# tas var būt ļoti noderīgi, ja mums ir ļoti liela tabula ar miljoniem ierakstu, un mēs vēlamies ietaupīt atmiņu, jo mazāki datu tipi aizņem mazāk atmiņas, un tas var uzlabot veiktspēju datu apstrādē un analīzē, jo mazāki datu tipi ļauj apstrādāt vairāk datu vienlaikus un samazina atmiņas patēriņu.
# bet jābūt uzmanīgiem, jo ja mēs izvēlamies pārāk mazu
# piemers uint8 uzstādīšanai vecumam
df["age"] = 30 # pievienojam jaunu kolonu "age" ar vērtību 30 katram produktam DataFrame, lai redzētu, kā pievienot jaunu kolonu ar vienādu vērtību visiem ierakstiem   
df["age"] = df["age"].astype("uint8") # pārvēršam "age" kolonnas datu tipu uz uint8, lai ietaupītu atmiņu, ja zinām, ka vecuma vērtības nekad nebūs lielākas par 255

# apskatamies datu tipus atkal
df.info() # df.info() funkcija izvadām vispārīgu informāciju par DataFrame, tostarp datu tipu, nulles vērtībām, un atmiņas patēriņu, lai redzētu, kā datu tipi ir mainījušies pēc pārvēršanas uz uint8

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  10 non-null     str
 1   name        10 non-null     str
 2   category    10 non-null     str
 3   price       10 non-null     float64
 4   in_stock    10 non-null     bool
 5   supplier    10 non-null     str
 6   quantity    10 non-null     int64
 7   age         10 non-null     uint8
dtypes: bool(1), float64(1), int64(1), str(4), uint8(1)
memory usage: 632.0 bytes

In [ ]:
# praktisks ieteikums
# necilāt standarta datu tipus līdz rodas nepieciešamība
# tas varētu būt noderīgi, ja ir ļoti daudz kolonnu un vai rindu
# piemēram 100miljons rindām no int64 uz uint8 mēs ietaupītu
# ap 700MB atmiņas, kas var būt ļoti noderīgi, ja strādājam ar lieliem datu kopumiem un vēlamies uzlabot veiktspēju datu apstrādē un analīzē, jo mazāki datu tipi ļauj apstrādāt vairāk datu vienlaikus un samazina atmiņas patēriņu.

In [79]:
# vēl viena ātrā uzvara ir df.describe()
# Tā mums sniedz ieskaut pēc noklusējuma par skaitliskām kolonnām
df.describe()

           price  quantity   age
count  10.000000      10.0  10.0
mean    7.072000      25.0  30.0
std     5.529747       0.0   0.0
min     0.890000      25.0  30.0
25%     3.512500      25.0  30.0
50%     5.950000      25.0  30.0
75%     7.147500      25.0  30.0
max    18.500000      25.0  30.0

In [84]:
# ja interesē tikai kategoriskās, string kolonnas 
df.describe(include='str')
# Pandas 2 lietojas df.describe(inlude='O') kur O ir no angļu valodas object, kas ir datu tips, ko pandas izmanto string kolonnām, un tas ļauj mums iegūt aprakstošo statistiku tikai par kategoriskajām, string kolonnām DataFrame, piemēram, unikālo vērtību skaitu, visbiežāk sastopamo vērtību, un to biežumu.

       product_id         name category      supplier
count          10           10       10            10
unique         10           10        4             8
top          P001  Notebook A5   Office  Baltic Paper
freq            1            1        3             2

In [85]:
# vēl viena ātrā uzvara value_counts()
# ar to saskataim vērtības kāda kolonnā teiksim category šeit
df["category"].value_counts() # df["category"].value_counts() funkcija izvadām unikālo vērtību skaitu un to biežumu "category" kolonnā, lai redzētu, kādas kategorijas ir un cik reižu katra kategorija parādās DataFrame

category
Office         3
Electronics    3
Lifestyle      2
Kitchen        2
Name: count, dtype: int64

In [87]:
category_value_counts = df["category"].value_counts() # saglabājam "category" kolonnas unikālo vērtību skaitu un to biežumu mainīgajā category_value_counts, lai varētu ar to turpmāk strādāt
print(category_value_counts) # izvadām category_value_counts, lai redzētu
# un kas tips ir pats mainīgais?
print(type(category_value_counts)) # izvadām category_value_counts datu tipu, lai redzētu, kāda Python datu struktūra tā ir

category
Office         3
Electronics    3
Lifestyle      2
Kitchen        2
Name: count, dtype: int64
<class 'pandas.Series'>

In [88]:
# savukārt pati df ir protams DataFrama kas ir vairāku Series kopums būtība plus metodes darbam
print(type(df))

<class 'pandas.DataFrame'>

In [89]:
# apskatam tagad kādi ir mums kolonu nosaukumi
df.columns

Index(['product_id', 'name', 'category', 'price', 'in_stock', 'supplier',
       'quantity', 'age'],
      dtype='str')

In [93]:
# kādas ir mūsu tabulas dimensijas (shape)?
print("Dimensijas:", df.shape)
# garums
print("Tabulas garums", len(df), "tas pats ", df.shape[0]) # izvadām DataFrame garumu, lai redzētu, cik rindu ir tabulā

Dimensijas: (10, 8)
Tabulas garums 10 tas pats  10

In [94]:
# attiecigi kolonu skaits
print("Kolonnu skaits", len(df.columns), "tas pats ", df.shape[1]) # izvadām DataFrame kolonnu skaitu, lai redzētu, cik kolonu ir tabulā

Kolonnu skaits 8 tas pats  8

In [95]:
# nedaudz ieskaits filtros
# piemēram visi produkti zem 3.50
cheap_products_df = df[df["price"] < 3.50] # izveidojam jaunu DataFrame, kurā ir tikai tie produkti, kuru "price" kolonnas vērtība ir mazāka par 3.50, lai redzētu, kā filtrēt DataFrame pēc noteikta nosacījuma
cheap_products_df # izvadām cheap_products_df, lai redzētu,

,product_id,name,category,price,in_stock,supplier,quantity,age
0,P001,Notebook A5,Office,2.49,True,Baltic Paper,25,30
1,P002,Ballpoint Pen Blue,Office,0.89,True,Riga Supplies,25,30
6,P007,Sticky Notes Set,Office,3.10,True,Baltic Paper,25,30

In [96]:
# es varu vienlaicīgi uzdot vairākus filtrus
# piemēram tika zem 3.50 un tikai no Baltic Paper
df[(df["price"] < 3.50) & (df["supplier"] == "Baltic Paper")]  # izveidojam jaunu DataFrame, kurā ir tikai tie produkti, kuru "price" kolonnas vērtība ir mazāka par 3.50 un "supplier" kolonnas vērtība ir "Baltic Paper", lai redzētu, kā filtrēt DataFrame pēc vairākiem nosacījumiem

,product_id,name,category,price,in_stock,supplier,quantity,age
0,P001,Notebook A5,Office,2.49,True,Baltic Paper,25,30
6,P007,Sticky Notes Set,Office,3.10,True,Baltic Paper,25,30

In [97]:
# es varētu tikai meklēt ar daļēju vārdu - drusku lēnak bet var
# piemēram supplier vārdā jābūt vārdam Paper
df[df["supplier"].str.contains("Paper", na=False)] # izveidojam ja

,product_id,name,category,price,in_stock,supplier,quantity,age
0,P001,Notebook A5,Office,2.49,True,Baltic Paper,25,30
6,P007,Sticky Notes Set,Office,3.10,True,Baltic Paper,25,30

In [99]:
# nomainīsi index 6 supplier vērtību
df.at[6, "supplier"] = "Baltic paper firma" # nomainām DataFrame rindiņas ar index 6 "supplier" kolonnas vērtību uz "Baltic Paper", lai redzētu, kā mainīt konkrētas rindiņas un kolonnas vērtību DataFrame
# apskatam visu tabulu, lai redzētu, ka izmaiņas ir veiktas
df

,product_id,name,category,price,in_stock,supplier,quantity,age
0,P001,Notebook A5,Office,2.49,True,Baltic Paper,25,30
1,P002,Ballpoint Pen Blue,Office,0.89,True,Riga Supplies,25,30
2,P003,Desk Lamp Mini,Electronics,18.50,False,Home Light,25,30
3,P004,Water Bottle 750ml,Lifestyle,7.20,True,Nordic Home,25,30
4,P005,USB-C Cable 1m,Electronics,6.99,True,Tech Bridge,25,30
5,P006,Coffee Mug Classic,Kitchen,4.75,True,Ceramica,25,30
6,P007,Sticky Notes Set,Office,3.10,True,Baltic paper firma,25,30
7,P008,Wireless Mouse,Electronics,14.90,True,Tech Bridge,25,30
8,P009,Tote Bag Canvas,Lifestyle,5.50,False,Urban Basic,25,30
9,P010,Tea Box Herbal,Kitchen,6.40,True,Green Leaf,25,30

In [100]:
# ja gribam case insensitive meklēšanu
df[df["supplier"].str.contains("paper", case=False, na=False)] # izve

,product_id,name,category,price,in_stock,supplier,quantity,age
0,P001,Notebook A5,Office,2.49,True,Baltic Paper,25,30
6,P007,Sticky Notes Set,Office,3.10,True,Baltic paper firma,25,30

In [101]:
# jebkuru tabulu uzreiz var arī saglabāt pat bez mainīga
# saglabāsim uzreiz paper produktus
df[df["supplier"].str.contains("paper", case=False, na=False)].to_csv("../data/day3/paper_products.csv", index=False, encoding="utf-8") # izveidojam jaunu DataFrame, kurā ir tikai tie produkti, kuru "supplier" kolonnas vērtība satur "paper" (case insensitive), un saglabājam to CSV failā, nodrošinot, ka netiek saglabāts indekss un tiek izmantots UTF-8 kodējums

In [ ]:
from __future__ import annotations

import json
from pathlib import Path

try:
    import pandas as pd
except ModuleNotFoundError as exc:
    raise SystemExit(
        "Šim notebook ir vajadzīgs pandas. Vispirms instalējiet to, piemēram: pip install pandas"
    ) from exc


def find_repo_root() -> Path:
    """Atrod projekta saknes mapi gan skripta, gan Jupyter izpildes gadījumā."""
    candidates: list[Path] = []

    try:
        candidates.append(Path(__file__).resolve().parents[1])
    except NameError:
        pass

    cwd = Path.cwd().resolve()
    candidates.extend([cwd, cwd.parent])

    for candidate in candidates:
        if (candidate / "data" / "day3").exists():
            return candidate

    return cwd


REPO_ROOT = find_repo_root()
DATA_DIR = REPO_ROOT / "data" / "day3"

## 1. Pārbaudām, vai datu faili eksistē

Pirms datu nolasīšanas ir laba prakse pārbaudīt failu ceļus.

In [ ]:
data_files = sorted(DATA_DIR.glob("*"))
print("Datu mape:", DATA_DIR.resolve())
print("Atrasti faili:")
for path in data_files:
    print("-", path.name)

## 2. Nolasām vienkāršu JSON failu

`products_basic.json` ir vienkāršs, plakans `JSON` fails.
Tas satur produktu objektu sarakstu.
Šādu struktūru ir visvieglāk pārveidot tabulā.

In [ ]:
products_json_path = DATA_DIR / "products_basic.json"

with products_json_path.open("r", encoding="utf-8") as file:
    products_data = json.load(file)

print("Python tips:", type(products_data))
print("Ierakstu skaits:", len(products_data))

Apskatīsim vienu elementu no saraksta.

In [ ]:
products_data[0]

Katrs elements ir Python vārdnīca.

In [ ]:
print("Pirmā elementa tips:", type(products_data[0]))
print("Pirmā elementa atslēgas:", list(products_data[0].keys()))

## 3. Ejam cauri JSON ierakstiem ar ciklu

Pirms lietot `pandas`, ir vērts apskatīt neapstrādātos datus tieši Python
struktūrās.

In [ ]:
for product in products_data[:3]:
    print(product["product_id"], "-", product["name"], "-", product["price"])

## 4. Pārveidojam vienkāršu JSON par DataFrame

Sarakstu ar vārdnīcām bieži var uzreiz pārvērst par `pandas DataFrame`.

In [ ]:
products_df = pd.DataFrame(products_data)
products_df

## 5. Apskatām DataFrame

Šīs ir pirmās komandas, ar kurām vajadzētu kļūt ērtāk strādāt.

In [ ]:
products_df.head()

In [ ]:
products_df.shape

In [ ]:
products_df.columns

In [ ]:
products_df.dtypes

In [ ]:
products_df.info()

## 6. Vienkārša kolonnu atlase

Varam atlasīt vienu kolonnu vai vairākas kolonnas.

In [ ]:
products_df["name"]

In [ ]:
products_df[["product_id", "name", "category", "price"]]

## 7. Filtrējam rindas

Šeit atlasām tikai elektronikas produktus.

In [ ]:
products_df[products_df["category"] == "Electronics"]

Varam kombinēt arī vairākus nosacījumus.

In [ ]:
products_df[(products_df["category"] == "Electronics") & (products_df["price"] > 10)]

## 8. Kārtojam vērtības

Kārtošana ir viens no pirmajiem praktiskajiem datu analīzes uzdevumiem.

In [ ]:
products_df.sort_values("price")

In [ ]:
products_df.sort_values("price", ascending=False)

## 9. Izveidojam jaunas kolonnas

Jaunas vērtības varam aprēķināt no jau esošajām kolonnām.

In [ ]:
products_df["price_with_vat"] = (products_df["price"] * 1.21).round(2)
products_df["name_upper"] = products_df["name"].str.upper()
products_df

## 10. Grupējam un veidojam kopsavilkumu

Šis ir līdzīgi vienkāršai Excel PivotTable pieejai.

In [ ]:
products_df.groupby("category")["price"].mean().sort_values(ascending=False)

In [ ]:
products_summary = (
    products_df.groupby("category")
    .agg(
        product_count=("product_id", "count"),
        average_price=("price", "mean"),
        max_price=("price", "max"),
    )
    .round(2)
)
products_summary

## 11. Nolasām ligzdotu JSON failu

`orders_nested.json` ir sarežģītāks piemērs.
Šis fails nav tikai saraksts. Tas ir objekts ar metadatiem un ar `orders`
sarakstu tā iekšpusē.

In [ ]:
orders_json_path = DATA_DIR / "orders_nested.json"

with orders_json_path.open("r", encoding="utf-8") as file:
    orders_document = json.load(file)

print("Augšējā līmeņa tips:", type(orders_document))
print("Augšējā līmeņa atslēgas:", list(orders_document.keys()))

Apskatīsim atskaites metadatus.

In [ ]:
print("Atskaites nosaukums:", orders_document["report_name"])
print("Izveidots:", orders_document["generated_at"])
print("Valūta:", orders_document["currency"])

Paši ieraksti atrodas laukā `orders`.

In [ ]:
orders_list = orders_document["orders"]
print("Pasūtījumu skaits:", len(orders_list))
orders_list[0]

## 12. Piekļuve ligzdotām vērtībām manuāli

Tas ir noderīgi, kamēr vēl tikai mācāmies saprast `JSON` struktūras.

In [ ]:
first_order = orders_list[0]

print("Pasūtījuma ID:", first_order["order_id"])
print("Klienta vārds:", first_order["customer"]["name"])
print("Klienta pilsēta:", first_order["customer"]["city"])
print("Maksājuma statuss:", first_order["payment"]["status"])
print("Pirmā pasūtītā prece:", first_order["items"][0]["product_id"])

## 13. Izlīdzinām ligzdotu JSON ar ciklu

Šeit veidojam vienu rindu katram pasūtījumam.
Dažiem laukiem apzināti izmantojam `.get()`, jo ne visiem pasūtījumiem ir
pilnīgi vienāda struktūra.

In [ ]:
order_rows = []

for order in orders_list:
    items = order.get("items", [])
    total_quantity = sum(item["quantity"] for item in items)
    items_total = sum(item["quantity"] * item["unit_price"] for item in items)
    delivery_cost = order.get("delivery", {}).get("cost", 0)
    total_amount = round(items_total + delivery_cost, 2)

    order_rows.append(
        {
            "order_id": order["order_id"],
            "customer_id": order["customer"]["customer_id"],
            "customer_name": order["customer"]["name"],
            "city": order["customer"]["city"],
            "loyalty_tier": order["customer"].get("loyalty_tier"),
            "item_count": len(items),
            "total_quantity": total_quantity,
            "items_total": round(items_total, 2),
            "delivery_type": order.get("delivery", {}).get("type"),
            "delivery_cost": delivery_cost,
            "payment_method": order.get("payment", {}).get("method"),
            "payment_status": order.get("payment", {}).get("status"),
            "coupon_code": order.get("coupon_code"),
            "total_amount": total_amount,
        }
    )

orders_df = pd.DataFrame(order_rows)
orders_df

## 14. Apskatām trūkstošās vērtības

Pēc ligzdota `JSON` izlīdzināšanas bieži parādās trūkstošas vērtības.

In [ ]:
orders_df.isna().sum()

Piemēram, ne visiem pasūtījumiem ir `coupon_code` vai `loyalty_tier`.

In [ ]:
orders_df[["order_id", "loyalty_tier", "coupon_code", "delivery_cost"]]

## 15. Filtrējam rezultātu no ligzdotā JSON

Šeit atstājam tikai apmaksātos pasūtījumus, kuros ir vismaz viena prece.

In [ ]:
paid_orders_df = orders_df[
    (orders_df["payment_status"] == "paid") & (orders_df["item_count"] > 0)
]
paid_orders_df

## 16. Nolasām CSV failus ar pandas

`CSV` jau ir tabulveida formāts, tāpēc `pandas` to var nolasīt tieši.

In [ ]:
sales_january_path = DATA_DIR / "sales_january.csv"
sales_february_path = DATA_DIR / "sales_february.csv"
products_csv_path = DATA_DIR / "products.csv"

sales_january_df = pd.read_csv(sales_january_path)
sales_february_df = pd.read_csv(sales_february_path)
products_lookup_df = pd.read_csv(products_csv_path)

In [ ]:
sales_january_df.head()

In [ ]:
sales_january_df.shape

In [ ]:
sales_january_df.dtypes

In [ ]:
sales_january_df.info()

## 17. Pārveidojam kolonnu datu tipus

Datumu kolonnas parasti jāpārveido atbilstošā tipā.

In [ ]:
sales_january_df["date"] = pd.to_datetime(sales_january_df["date"])
sales_february_df["date"] = pd.to_datetime(sales_february_df["date"])

sales_january_df.dtypes

## 18. Trūkstošās vērtības CSV datos

Pamaniet, ka kolonnā `discount_pct` ir trūkstošas vērtības.

In [ ]:
sales_january_df.isna().sum()

In [ ]:
sales_january_df[sales_january_df["discount_pct"].isna()]

Šīs trūkstošās atlaides varam aizpildīt ar `0`.

In [ ]:
sales_january_df["discount_pct"] = sales_january_df["discount_pct"].fillna(0)
sales_february_df["discount_pct"] = sales_february_df["discount_pct"].fillna(0)

sales_january_df.isna().sum()

## 19. Atlasām un filtrējam CSV datus

In [ ]:
sales_january_df[["sale_id", "date", "product_id", "store", "units_sold"]]

In [ ]:
sales_january_df[sales_january_df["units_sold"] >= 10]

In [ ]:
sales_january_df[sales_january_df["store"] == "Riga-Center"]

## 20. Veidojam aprēķinātās kolonnas

Vispirms pievienojam produktu cenas pārdošanas tabulai ar `merge()`.

In [ ]:
sales_january_enriched_df = sales_january_df.merge(
    products_lookup_df[["product_id", "name", "category", "price"]],
    on="product_id",
    how="left",
)

sales_january_enriched_df.head()

Tagad varam aprēķināt bruto ieņēmumus un ieņēmumus pēc atlaides.

In [ ]:
sales_january_enriched_df["gross_revenue"] = (
    sales_january_enriched_df["units_sold"] * sales_january_enriched_df["price"]
).round(2)

sales_january_enriched_df["net_revenue"] = (
    sales_january_enriched_df["gross_revenue"]
    * (1 - sales_january_enriched_df["discount_pct"] / 100)
).round(2)

sales_january_enriched_df.head()

## 21. Kārtojam un veidojam pārdošanas kopsavilkumus

In [ ]:
sales_january_enriched_df.sort_values("net_revenue", ascending=False)

In [ ]:
sales_by_store_df = (
    sales_january_enriched_df.groupby("store")
    .agg(
        total_units=("units_sold", "sum"),
        total_revenue=("net_revenue", "sum"),
        average_discount=("discount_pct", "mean"),
    )
    .round(2)
    .sort_values("total_revenue", ascending=False)
)
sales_by_store_df

In [ ]:
sales_by_category_df = (
    sales_january_enriched_df.groupby("category")
    .agg(
        total_units=("units_sold", "sum"),
        total_revenue=("net_revenue", "sum"),
    )
    .round(2)
    .sort_values("total_revenue", ascending=False)
)
sales_by_category_df

## 22. Apvienojam mēnešu tabulas ar concat()

Janvāra un februāra failiem ir vienādas kolonnas, tāpēc vertikāla
apvienošana ir vienkārša.

In [ ]:
all_sales_df = pd.concat([sales_january_df, sales_february_df], ignore_index=True)
all_sales_df

In [ ]:
all_sales_df.shape

## 23. Apvienojam pārdošanas datus ar produktu tabulu

`merge()` apvieno divas tabulas pēc kopīgas atslēgas.

In [ ]:
all_sales_enriched_df = all_sales_df.merge(products_lookup_df, on="product_id", how="left")
all_sales_enriched_df.head()

Pievienosim aprēķinātās ieņēmumu kolonnas arī apvienotajiem datiem.

In [ ]:
all_sales_enriched_df["gross_revenue"] = (
    all_sales_enriched_df["units_sold"] * all_sales_enriched_df["price"]
).round(2)

all_sales_enriched_df["net_revenue"] = (
    all_sales_enriched_df["gross_revenue"]
    * (1 - all_sales_enriched_df["discount_pct"] / 100)
).round(2)

all_sales_enriched_df.head()

## 24. Analīze pa abiem mēnešiem kopā

Tagad varam veidot kopsavilkumus par abiem mēnešiem.

In [ ]:
monthly_store_summary_df = (
    all_sales_enriched_df.groupby("store")
    .agg(
        total_units=("units_sold", "sum"),
        total_revenue=("net_revenue", "sum"),
        row_count=("sale_id", "count"),
    )
    .round(2)
    .sort_values("total_revenue", ascending=False)
)
monthly_store_summary_df

In [ ]:
product_summary_df = (
    all_sales_enriched_df.groupby(["category", "name"])
    .agg(
        total_units=("units_sold", "sum"),
        total_revenue=("net_revenue", "sum"),
    )
    .round(2)
    .sort_values(["category", "total_revenue"], ascending=[True, False])
)
product_summary_df

## 25. Vienkārša pivot tabula

Šis ir viens no biežākajiem soļiem Excel lietotājiem, kuri sāk strādāt ar
`pandas`.

In [ ]:
pivot_table_df = pd.pivot_table(
    all_sales_enriched_df,
    index="store",
    columns="category",
    values="net_revenue",
    aggfunc="sum",
    fill_value=0,
).round(2)

pivot_table_df

## 26. JSON un CSV salīdzinājums

Īss salīdzinājums:
- `CSV` ir ērtāks, ja dati jau ir tabulas formā
- vienkāršu `JSON` bieži var tieši pārveidot par tabulu
- ligzdotu `JSON` parasti vispirms vajag apskatīt un izlīdzināt

Zemāk salīdzinām trīs galveno tabulu izmērus.

In [ ]:
print("products_df izmērs:", products_df.shape)
print("orders_df izmērs:", orders_df.shape)
print("all_sales_enriched_df izmērs:", all_sales_enriched_df.shape)

## 27. Rezultātu eksports

Reālos darba procesos notīrītos vai apkopotos datus bieži saglabājam failos.

In [ ]:
output_dir = DATA_DIR / "outputs"
output_dir.mkdir(exist_ok=True)

sales_by_store_df.to_csv(output_dir / "sales_by_store_january.csv")
monthly_store_summary_df.to_csv(output_dir / "sales_by_store_all_months.csv")
orders_df.to_json(output_dir / "orders_flattened.json", orient="records", indent=2)

print("Faili saglabāti mapē:", output_dir.resolve())

## 28. Idejas patstāvīgai praksei

Pamēģiniet paši:
- atlasīt tikai `Office` kategorijas produktus
- atrast visdārgāko produktu
- aprēķināt kopējos janvāra ieņēmumus pa produktiem
- atrast pasūtījumus, kuriem trūkst `loyalty_tier`
- sakārtot visus pārdošanas ierakstus pēc `units_sold`
- eksportēt tikai Electronics pārdošanas datus atsevišķā `CSV` failā

Zem šīs vietas varat pievienot savas šūnas.

In [ ]:
# Rakstiet savu prakses kodu šeit.